services:
  db:
    image: postgres:16-alpine
    container_name: pg-webhook
    environment:
      POSTGRES_DB: webhook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d webhook" ]
      interval: 5s
      timeout: 3s
      retries: 10

  webhook-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: webhook-service:dev
    container_name: webhook-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: "8087"

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/webhook"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      PAYMENT_SERVICE_BASE_URL: "http://host.docker.internal:8087"
    ports:
      - "8088:8088"

volumes:
  pgdata:
